SELECT * FROM speciality;
INSERT INTO speciality(name)
VALUES ('Anatomia Patológica'),
('Anestesiologia'),
('Angiologia e Cirurgia Vascular'),
('Cardiologia'),
('Cardiologia Pediátrica'),
('Cirurgia Cardíaca'),
('Cirurgia Cardiotorácica'),
('Cirurgia Geral'),
('Cirurgia Maxilo-Facial'),
('Cirurgia Pediátrica'),
('Cirurgia Plástica Reco. e Est.'),
('Cirurgia Torácica'),
('Dermato-Venereologia'),
('Doenças Infecciosas'),
('Endocrinologia e Nutrição'),
('Estomatologia'),
('Farmacologia Clínica'),
('Gastrenterologia'),
('Genética Médica'),
('Ginecologia/Obstetrícia'),
('Hematologia Clínica'),
('Imunoalergologia'),
('Imunohemoterapia'),
('Medicina Desportiva'),
('Medicina do Trabalho'),
('Especialidade Medicina Física e de Reabilitação'),
('Medicina Geral e Familiar'),
('Medicina Intensiva'),
('Medicina Interna'),
('Medicina Legal'),
('Medicina Nuclear'),
('Medicina Tropical'),
('Nefrologia'),
('Neurocirurgia'),
('Neurologia'),
('Neurorradiologia'),
('Oftalmologia'),
('Oncologia Médica'),
('Ortopedia'),
('Otorrinolaringologia'),
('Patologia Clínica'),
('Pediatria'),
('Pneumologia'),
('Psiquiatria'),
('Psiquiatria da Infância e da Adolescência'),
('Radiologia'),
('Radioncologia'),
('Reumatologia'),
('Saúde Pública'),
('Urologia');
