SELECT * FROM speciality;
INSERT INTO speciality(name, price)
VALUES ('Anatomia Patológica', 60),
('Anestesiologia', 50),
('Angiologia e Cirurgia Vascular', 50),
('Cardiologia', 50),
('Cardiologia Pediátrica', 50),
('Cirurgia Cardíaca', 50),
('Cirurgia Cardiotorácica', 50),
('Cirurgia Geral', 50),
('Cirurgia Maxilo-Facial', 50),
('Cirurgia Pediátrica', 50),
('Cirurgia Plástica Reco. e Est.', 50),
('Cirurgia Torácica', 50),
('Dermato-Venereologia', 50),
('Doenças Infecciosas', 50),
('Endocrinologia e Nutrição', 50),
('Estomatologia', 50),
('Farmacologia Clínica', 50),
('Gastrenterologia', 50),
('Genética Médica', 50),
('Ginecologia/Obstetrícia', 50),
('Hematologia Clínica', 50),
('Imunoalergologia', 50),
('Imunohemoterapia', 50),
('Medicina Desportiva', 50),
('Medicina do Trabalho', 50),
('Especialidade Medicina Física e de Reabilitação', 50),
('Medicina Geral e Familiar', 50),
('Medicina Intensiva', 50),
('Medicina Interna', 50),
('Medicina Legal', 50),
('Medicina Nuclear', 50),
('Medicina Tropical', 50),
('Nefrologia', 50),
('Neurocirurgia', 50),
('Neurologia', 50),
('Neurorradiologia', 50),
('Oftalmologia', 50),
('Oncologia Médica', 50),
('Ortopedia', 50),
('Otorrinolaringologia', 50),
('Patologia Clínica', 50),
('Pediatria', 50),
('Pneumologia', 50),
('Psiquiatria', 50),
('Psiquiatria da Infância e da Adolescência', 50),
('Radiologia', 50),
('Radioncologia', 50),
('Reumatologia', 50),
('Saúde Pública', 50),
('Urologia', 65);
